### ISSUE TITLE
In .gitignore: inconsistent reference to dirs under "sites"

### ISSUE THREAD

**Issue by alisonjo2786** [pantheon-systems/example-drops-8-composer#100]
In a couple cases, the .gitignore file points to `web/sites/*/[etc]`, but for ignoring the files directory, it points to `web/sites/default/files` -- I understand that multisite isn't supported so the * wildcard is irrelevant, but still, it seems like an unnecessary customization of the .gitignore file included in vanilla drupal (from `drupal-composer/drupal-project`).

Either way, I think it should probably be consistent -- obviously, I vote for changing the files dir pointer to `web/sites/*/files` :)
https://github.com/pantheon-systems/example-drops-8-composer/blob/master/.gitignore#L54

(Yes, yes I am doing a full comparison of vanilla drupal codebase (via `drupal-composer/drupal-project`) versus `pantheon-systems/example-drops-8-composer` :) )

**Comment by stevector** [comment]
> (Yes, yes I am doing a full comparison of vanilla drupal codebase (via drupal-composer/drupal-project) versus pantheon-systems/example-drops-8-composer :) )

Awesome! In my opinion we need to document and/or resolve all discrepancies with `drupal-composer/drupal-project`

Have you seen https://github.com/pantheon-systems/example-drops-8-composer/issues/61 ?

**Comment by alisonjo2786** [comment]
No I have not, thanks for the tip!

More from my comparison funtivity:
(or you can find it on the composer-workflow channel, Aug 10, 7pm EDT)
https://pantheon-community.slack.com/archives/C5EM55T0X/p1502412641954639?thread_ts=1502406197.415477&cid=C5EM55T0X

#61 is super helpful for me knowing/understanding what's needed and why, thanks again!

**Comment by alisonjo2786** [comment]
(woah, sorry I left this open so long -- closing due to my own inactivity :) )
