### ISSUE TITLE
Support Request: Pantheon Multidev Environment all named ci-# or pr-#

### ISSUE THREAD

**Issue by finteractive** [pantheon-systems/example-drops-8-composer#116]
We're using Circle + a forked version of example-drops-8-composer (Forked on Sept 13th) 

https://github.com/pantheon-systems/example-drops-8-composer/commit/d468d61952f0fd0773df58b333d9ab3ac7692083

**What I did**
* Create a git branch locally from master "feature-x"
* Push to github
* create a GH Pull request

**What happened**
This triggers off the workflow, but the multidev environment it isn't named after the branch. We get ci-102 or pr-10 or whatever the # of the ID in github.

**What I expected**
I was expecting the PR to create a multi-dev call "feature-x-project.pantheonsite.io"

We've tried editing the CircleCI "Advanced Settings" with various settings...
* Only build pull requests = ON 

This removes the ci-102 builds but we still don't get the multidev environments named after the PR's branch. 

Possibly related: We noticed when we "merge + delete" pull requests in github the related pantheon multidev is not deleted automated. We're cleaning them up manually right now.

**Questions**

* Am I right to assume the multidev should be named after the branch? 
* There was a release a day after our build was forked. Do you think we need to move to that commit?
* What are the expected CircleCI advanced settings? (Current settings copied here for reference)

---
**GitHub Status updates**

By default, we update the status of every pushed commit with GitHub's status API. If you'd like to turn this off (if, for example, this is conflicting with another service), you can do so below.

- [x] On 
- [ ] Off

**Build forked pull requests**

Run builds for pull requests from forks. CircleCI will automatically update the commit status shown on GitHub's pull request page.

- [ ] On 
- [x] Off

**Pass secrets to builds from forked pull requests**

Run builds for fork pull request changes with this project's configuration, environment variables, and secrets.

There are serious security concerns with this setting (see the documentation for details.) If you have SSH keys, sensitive env vars or AWS credentials stored in your project settings and untrusted forks can make pull requests against your repo, then this option isn't for you!

- [x] On 
- [ ] Off

**Only build pull requests**

By default, we will build all the commits for this project. Once turned on, we will only build branches that have associated pull requests open. Note: For your default branch, we will always build all commits.

- [x] On 
- [ ] Off

**Auto-cancel redundant builds (Does not apply to workflows)**

With the exception of your default branch, we will automatically cancel any queued or running builds on a branch when a newer build is triggered on that same branch. This feature will only apply to builds triggered by pushes to GitHub.

- [x] On 
- [ ] Off

**Comment by greg-1-anderson** [comment]
Old versions of the tool named the multidev environment after the branch name. The problem with this is that some people did not realize that these names are necessarily truncated, as multidev names can be no longer than 11 characters. That leaves you with only 8 significant characters in the branch name after the "pr-" is prepended.

To avoid this problem, we switched to naming pull request multidev environments after the pull request number instead of the branch name.

**Comment by finteractive** [comment]
I see how people could be confused, but there's also something to be said for having stable multidev environment names for collaborating with clients & QA teams.

We're merging all our feature PR's into a "QA" multidev branch. We merge and then run  3rd party tools w/ accessibility scanners that expect a fixed URL (changing the URL loses the history which we want to track over time). Basically we want to make sure out merge feature branches work well, before merging into master.

Is there any way to update the configuration to do the old behaviour ?
Or have some specific PR text pattern map to a specific multidev environment?

**Comment by greg-1-anderson** [comment]
You may, of course, fork the test scripts and define `TERMINUS_ENVIRONMENT` to follow whatever pattern you'd like. Look at older versions of the project to see the reductions previously done to the branch name to ensure that the multidev name is always valid. It is recommended to name your environments starting with `pr-`, because if you do this, they will be automatically deleted once their corresponding pull request is closed or merged.

I'm not sure whether we will support the old naming convention as a supported pattern or not.

**Comment by finteractive** [comment]
Can you point me in the right direction where to apply these customization? (We're doing out best to keep as close to your default configuration as possible).

It appears that a recent commit to circle 2.0 moved the logic from this project to a docker environment.  

```./.circleci/scripts/00-set-environment``` to ```/build-tools-ci/scripts/set-environment```

Where is /build-tools-ci/'s scripts defined?

**Comment by greg-1-anderson** [comment]
See [the comment in the script](https://github.com/pantheon-systems/example-drops-8-composer/blob/master/.circleci/config.yml#L54). You can copy the script into your local scripts directory and modify it. If you want to stay as close to the default configuration as possible, maybe make your set-environment script call (source) the Docker-based script, and then modify the environment variables as it wishes.

**Comment by finteractive** [comment]
Awesome - Thank you for the help!
