### ISSUE TITLE
Command 'composer create-project' failed with exit code 127

### ISSUE THREAD

**Issue by aheaphy** [pantheon-systems/example-drops-8-composer#119]
After installing terminus and composer, and creating machine tokens for Git and CircleCI, I am getting the following error with `terminus build:project:create` :

```
sh: composer: command not found
[error]  Command `composer create-project --working-dir=/private/var/folders/t7/nws79l7d2njdv93c7l2bn5gr0000gn/T/local-sitegSZqNc pantheon-systems/example-drops-8-composer pantheon-d8-test -n ` failed with exit code 127
```
I am able to composer create-project with https://github.com/drupal-composer/drupal-project, with no issues, so not sure if this is something on my end or not? Any help would be appreciated.

**Comment by greg-1-anderson** [comment]
`terminus build:project:create` will `exec` composer. Maybe you have made `composer` an alias to something else, e.g. `php /path/to/composer`? From your shell, type `type composer` to find out.

To fix, make sure that Composer is named `composer` and exists on your `$PATH`

**Comment by aheaphy** [comment]
aah, in my usr/local/bin it was named composer.phar ... which was working for installing other drupal composer templates (https://github.com/drupal-composer/drupal-project), but not pantheon's, I removed the .phar and all is now set up ... thank you!
