### ISSUE TITLE
Why is Simple Block (simple_block) module required?

### ISSUE THREAD

**Issue by ptmkenny** [pantheon-systems/example-drops-8-composer#125]
I'm curious why the `composer.json` requires the Simple Block module.  Is this necessary for sites built using the Pantheon Build Tools, or is it just included for convenience?

**Comment by greg-1-anderson** [comment]
This is just an example repository; you may remove the simple block module if you don't want to use it. However, if you use the built-in System blocks you will run into problems, so simple block is enabled in its place as a gentle hint.
