### ISSUE TITLE
Save build artifacts in CircleCI

### ISSUE THREAD

**Issue by deviantintegral** [pantheon-systems/example-drops-8-composer#131]
It would be good if the default build scripts could save the resulting build as an archive in CircleCI. This gives teams an extra layer of security (knowing in the future what exactly was deployed), and can help with debugging where a developer can download the _exact_ build that was deployed.

At first, I thought this wasn't needed as git is used for the deployment. However, `git push --force -q pantheon temp-work-ci-1:master` is used, which means that a force push could technically delete the history and prior builds.

**Comment by greg-1-anderson** [comment]
The authoritative history is stored in the GitHub repository; if you do not overwrite that, then you will not delete history for your work product. You are correct that the build results are overwritten every time via the `git push --force`, so there is no history of the build results at all.

The build results are quite large, so I am reluctant to save them in CircleCI for all users, when many probably won't use them or even know they are there. You may, of course, modify the Circle CI configuration of your projects to store the build results as Circle artifacts.

I'd accept a PR that had an appropriate rsync command in the default configuration, commented out.

**Comment by deviantintegral** [comment]
From [Circle's artifacts docs](https://circleci.com/docs/2.0/artifacts/#downloading-all-artifacts-for-a-build-on-circleci):

> Artifacts are designed to be useful around the time of the build. It is best practice not to rely on artifacts as a software distribution mechanism with long term future guarantees.

In which case, you'd have to write something to sync artifacts outside of Circle anyways. That's varied enough an example won't help, so I'll let this lie. Thanks!
