### ISSUE TITLE
09-cleanup-fixtures file is empty

### ISSUE THREAD

**Issue by wundo** [pantheon-systems/example-drops-8-composer#133]
Currently 
https://github.com/pantheon-systems/example-drops-8-composer/blob/master/.circleci/scripts/pantheon/09-cleanup-fixtures

Does nothing :(

**Comment by greg-1-anderson** [comment]
This repository is an example that demonstrates how to build a CI workflow for your project. This script is a placeholder for deleting things that are unneeded after the end of the test run. While there is nothing that needs to be removed in the base example repo, those who extend it might want to make use of this script.
