### ISSUE TITLE
PHP Version 7.0 in Composer versus Pantheon PHP Version 7.2

### ISSUE THREAD

**Issue by cnovak** [pantheon-systems/example-drops-8-composer#159]
I ran through the build tools documentation, and want to install a [module that depends on PHP 7.1 or greater](https://github.com/apigee/apigee-edge-drupal).  I see that the platform version in composer.json is set to "7.0.8":

```
"platform": {
            "php": "7.0.8"
        }
```

However, the pantheon.yml file has PHP 7.2:

```
php_version: 7.2
```

When I try to install the module that depends on 7.1, I get:

>[InvalidArgumentException]
Package drupal/apigee_edge at version has a PHP requirement incompatible with your PHP version (7.0.8)

Questions:
1. Should this composer project have the PHP version set to 7.0.8? Is there a reason for this?
2. Why does the composer file require 7.0, but the Pantheon site runs on 7.2?   
3. How can I install a module that needs 7.1 or above?  I am assuming I should change the composer.json platform requirement and pantheon.yml to be 7.1.

**Comment by greg-1-anderson** [comment]
Yes, you should change your platform:php setting if you'd like to use modules that require php 7.1.

The `php_version` in pantheon.yml selects the php version that this site happens to run on when it is running on Pantheon. The platform:php setting stipulates the minimum php version that can be used to run the site. You might run your site with an older version of php when running it locally, for example.

We could bump up the platform:php here if this commonly becomes an issue for folks.

**Comment by cnovak** [comment]
Thanks for info. I updated composer.json platform:php to be set to "7.1" and changed the php_version in Pantheon.yml to be "7.1" and can now install the module that requires 7.1 without errors.

I also updated the description of this issue to be more clear on what was happening when installing the module that depends on PHP 7.1.
