### ISSUE TITLE
[circleci] Destroy PR environment after merge or close

### ISSUE THREAD

**Issue by ElijahLynn** [pantheon-systems/example-drops-8-composer#161]
Not sure if this belongs here but the .circleci scripts are here so it must be close. 

I would like the scripts and documentation to support a "destroy after merge or close" workflow, so I don't have to manually destroy PR multidev environments. I think #160 would need to be resolved first so the multidev environment name creation is consistent enough to target the destroy.

**Comment by ElijahLynn** [comment]
Hrm, at https://pantheon.io/docs/guides/build-tools/merge/ it does say it should be deleted, but my first test it did not delete. Something funny is happening, testing some more.

**Comment by ElijahLynn** [comment]
Oh my, it did work this time, but instead of deleting the PR it came from it deleted ALL PR-N multidevs...

https://github.com/pantheon-systems/example-drops-8-composer/blob/master/.circleci/scripts/pantheon/04-merge-master#L24-L26

> # Delete old multidev environments associated with a PR that has been
# merged or closed.
terminus -n build:env:delete:pr "$TERMINUS_SITE" --yes

But $TERMINUS_SITE is the site ID and `terminus build:env:delete:pr --help` says 

> Delete all of the build environments matching the pattern for pull request branches, i.e., all multidevs whose name begins with "pr-".  

So this definitely needs some work. And I think it didn't delete the PR environment before because I tested it with the initial build which was CI-N, and it doesn't match that pattern.

**Comment by ElijahLynn** [comment]
In the triggered build I got this, meaning it was looking for all OPEN PRs, when it should look for all CLOSED PRs. 

> [notice] Call GitHub API: repos/ElijahLynn/pantheon-d8-composer-project-elijah/pulls?state=open
> 
>  [notice] Deleted the multidev environment pr-2.
> 
>  [notice] Deleted the multidev environment pr-3.
> 
>  [notice] Deleted the multidev environment pr-4.
> 
>  [notice] Deleted the multidev environment pr-5.
> 
>  [notice] Deleted the multidev environment pr-6.

**Comment by ElijahLynn** [comment]
It _seems_ like terminus-build-tools-plugin 2.x may not fetch all OPEN PRs anymore as I can see it has been heavily refactored. The docker build-tools-ci image doesn't have this though it isn't easy to test via that workflow. I will see about testing the build-tools-plugin 2.x locally.

**Comment by greg-1-anderson** [comment]
There are still problems with the multidev delete code; it works in some instances, but many users have reported problems.

I agree that the algorithm should be looking for CLOSED PRs. The current algorithm protects multidevs that are associated with a PR that is still open; it would be safer if it only deleted a PR if it could definitively find a PR that had been merged or closed.

**Comment by ElijahLynn** [comment]
> The current algorithm protects multidevs that are associated with a PR that is still open

In my example above, pr-{4..6} were associated with PRs still open, yet still deleted, so the protection has an edge case somewhere.

**Comment by greg-1-anderson** [comment]
If the code says "delete a PR unless it has an open PR", and the open PR check comes back with an error due to a bug, then the algorithm might delete a PR by mistake. If we switched it to say "only delete a PR if it has a closed/merged PR", and the closed/merge PR check comes back with an error due to a bug, then the algorithm might fail to delete a PR that it could have cleaned up. I think the later scenario is preferable.

**Comment by ryanschmidt** [comment]
@greg-1-anderson the later scenario does sound preferable. Is this still something we'd like to happen?

**Comment by ataylorme** [comment]
@ElijahLynn multidevs associated with PRs have been working for some time now (sorry this issue fell through the cracks). We also recently re-organized the CI scripts in this example repository.

Try out the changes to Build Tools (and this repo) and re-open this if you are still experiencing trouble.

**Comment by ElijahLynn** [comment]
Thanks, I trust it is all working now. I haven't been on a recent Pantheon project but will test this out on the next one I am on!
