### ISSUE TITLE
ScriptHandler.php coding standards?

### ISSUE THREAD

**Issue by alisonjo315** [pantheon-systems/example-drops-8-composer#183]
Hiya! Normal (for me) caveats -- I could be mistaken, I may have misunderstood, etc etc --

### Looking at [scripts/composer/ScriptHandler.php](https://github.com/pantheon-systems/example-drops-8-composer/blob/master/scripts/composer/ScriptHandler.php)...

I think the `{` characters are supposed to be on the same line as class/function/etc declarations -- just based on the examples on the [d.o OOP coding standards doc](https://www.drupal.org/docs/develop/standards/object-oriented-code#indenting) (...and based on the version of this file that's in [drupal-composer/drupal-project](https://github.com/drupal-composer/drupal-project/blob/8.x/scripts/composer/ScriptHandler.php) -- but the doc on d.o is a more compelling reason in my book).

So, for ScriptHandler.php, the change would look like this:
```diff
-class ScriptHandler
-{
+class ScriptHandler {
 
-  protected static function getDrupalRoot($project_root)
-  {
+  protected static function getDrupalRoot($project_root) {
```
(etc.)

ANYWAY, not urgent, just, lmk what y'all think -- if you agree, I'm happy to submit a PR with the new-line changes.  Thanks!

**Comment by greg-1-anderson** [comment]
I use PSR-2 in all of my projects. Since this is a Drupal-based project, using the Drupal coding standards for this file would make sense, especially if folks who fork this project automatically run code style checks over all php files in their project.

So, sure, I'd take that PR.

**Comment by alisonjo2786** [comment]
Cool!  I'll submit tomorrow.

Speaking of code style checks -- soooo I've been going about my life sans
PHP code sniffer til now 😇  but today I set it up, along with
drupal/coder, woo hoo.

Do you know if ppl generally just use drupal/coder (with its "Drupal" and
"DrupalPractice" standards) for this kind of thing, or is there some other
way ppl go about it? (If you happen to have a feel for what's "normal"!) --
I feel like it's prob the norm, based on the phpcs guidelines that come
with Drupal core, but then again, I don't actually think ppl enforce all
the description and explanatory comment rules, so maybe they use a sniffer
that's adapted to not complain as much about certain things..... Anyway,
not a big thing, just wondering if you know offhand what's "normal".

Thanks!

**Comment by greg-1-anderson** [comment]
Outside of the Drupalverse, it is pretty normal to set up phpcs to enforce PSR-2 coding standards fairly strictly. That's what I do. See [g1a/starter](https://github.com/g1a/starter#psr-2-checks-and-php-linting).

I don't have a good measure of what is common for Drupal contrib module developers.
