### ISSUE TITLE
Visual regression tests fails when live environment is not initialized

### ISSUE THREAD

**Issue by ataylorme** [pantheon-systems/example-drops-8-composer#200]
The live environment is used to compare the multidev against on a pull request. If live is not initialized the comparison fails. Maybe this isn't such a bad thing? cc @greg-1-anderson

**Comment by greg-1-anderson** [comment]
Works as designed, perhaps?  We could potentially do a check to see if the live environment exists, and abort the visual regression test if it does not. I don't know what the fastest way is, but `terminus env:info $TERMINUS_SITE.live` would work.

**Comment by ataylorme** [comment]
Yeah, we could return `1` if the live environment isn't initialized but the result is the same, a failed build, just saving ~10 seconds.

I'm inclined to leave this as-is but wanted a second opinion.

**Comment by greg-1-anderson** [comment]
I am indifferent; either is okay.
