### ISSUE TITLE
Document why each composer dependency is present

### ISSUE THREAD

**Issue by stevector** [pantheon-systems/example-drops-8-composer#222]
I think we should document why each package in `require` and `require-dev` is present. Doing so should make maintaining copies of this example easier on developers. I think the exercise will also lead us to finding that some packages are not necessary or are duplicative of others.

**Comment by ChristopherMatthews** [comment]
I agree, I started a new site this morning and manually removed the following packages as they are not really "required", but are more "recommended" or "suggested" packages:
- drupal/config_direct_save
- drupal/console and its dependencies
