### ISSUE TITLE
visual-regression-test.sh logic: not picking up "[vr]" in message

### ISSUE THREAD

**Issue by amaisano** [pantheon-systems/example-drops-8-composer#247]
I've tested a commit (non-master branch, HAS a PR open) with `[vr]` string present in both the commit title and commit message body, but the test is still being skipped. From what I could see in the logic, as long as the base conditions are reached (non-master, PR branch), if "[vr]" is present it should force the tests to run, regardless of composer.lock and composer.json status.

Commit:

```
testing [vr] again

[vr]
```

Output:

```
Creating cms_visual_regression ... done
[1BAttaching to cms_visual_regression
cms_visual_regression | 
cms_visual_regression | Processing pull request #276
cms_visual_regression | 
cms_visual_regression | Skipping visual regression tests since composer.lock has NOT changed
cms_visual_regression exited with code 0
```

Logic:

```
LAST_GIT_COMMIT_MESSAGE=$(git log -1 --pretty=%B)

# Always run visual tests if "[vr]" is in the last commit message
if [[ ${LAST_GIT_COMMIT_MESSAGE} != *"[vr]"* ]]...
```

**Comment by ataylorme** [comment]
> if "[vr]" is present it should force the tests to run, regardless of composer.lock and composer.json status.

Yes, this should be the case and I tested successfully when adding the functionality. 

Can you try running your job via ssh and seeing what the value of `LAST_GIT_COMMIT_MESSAGE` is?

**Comment by amaisano** [comment]
`final [vr] [VR] "[vr]" attempt` is what I'm getting in Semaphore's SSH of my build -- (ran `git log -1 --pretty=%B`). I'll update here below once I step through the normal scripts and get that envvar.

**Comment by amaisano** [comment]
Interesting. When I stepped through Semaphore in SSH with the same commands, I think it worked as expected:

`cms_visual_regression | Running visual regression tests because the latest commit message demands it`

**Comment by ataylorme** [comment]
Interesting. If you are debugging with SSH what does `git remote -v` show?

In the CI script you could set the remote/checkout the GitHub repo (though I am not sure why it is showing the Pantheon repo to begin with) or try updating `git log -1 --pretty=%B` to `git log -2 --pretty=%B`, which will get the commit messages of the last two commits and should have the custom commit before the `Build assets` commit.

**Comment by amaisano** [comment]
`--skip=1` is a quick fix here, which we're going to use for now (modifying `visual-regression-test.sh`. I'm not 100% sure where exactly the commits are altered to bump this, but I do know it is happening.
