### ISSUE TITLE
No such file or directory in /srv/bindings/3ff8997034df42a7a7b6fb7303d8fe9c/code/web/autoload.php

### ISSUE THREAD

**Issue by uceap-web** [pantheon-systems/example-drops-8-composer#25]
After manual install got: 

`Warning: require(/srv/bindings/3ff8997034df42a7a7b6fb7303d8fe9c/code/web/../vendor/autoload.php): failed to open stream: No such file or directory in /srv/bindings/3ff8997034df42a7a7b6fb7303d8fe9c/code/web/autoload.php on line 17 Fatal error: require(): Failed opening required '/srv/bindings/3ff8997034df42a7a7b6fb7303d8fe9c/code/web/../vendor/autoload.php' (include_path='.:/usr/share/pear:/usr/share/php') in /srv/bindings/3ff8997034df42a7a7b6fb7303d8fe9c/code/web/autoload.php on line 17 `

**Comment by uceap-web** [comment]
updating terminus (0.13.2) to the latest version (0.13.6) then running "terminus composer update --site=sitename --env=dev" fixed the problem.

**Comment by arshad** [comment]
Note: You need https://github.com/rvtraveller/terminus-composer to run the `terminus composer update` command.
