### ISSUE TITLE
GIT_FILE_MODIFIED() fails with bash / git error, preventing visual regression from running

### ISSUE THREAD

**Issue by aaronbauman** [pantheon-systems/example-drops-8-composer#279]
Not sure if this issue is limited to bitbucket, but GIT_FILE_MODIFIED() bash function is failing during `./.ci/test/visual-regression/run` with the following error:

```
fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
Skipping visual regression tests since composer.lock has NOT changed
```

This error results in viz reg never being run.

Here's an example: https://bitbucket.org/messageagency/pipe-test/addon/pipelines/home#!/results/32/steps/%7B88f65e38-88e5-4027-a9d0-ecefb7ad5e70%7D

**Comment by ataylorme** [comment]
Odd, it worked for me in all 3 scenarios testing on BitBucket (passing build links below)

- [`composer.lock` changed but `composer.json` did not](https://bitbucket.org/ataylorme/example-wp-composer-pipelines-test-2019-09-10/addon/pipelines/home#!/results/15/steps/%7Bd6a77c4d-d00a-4d03-8a67-672ece0c5cac%7D)
- [`[vr]` in the last commit message](https://bitbucket.org/ataylorme/example-wp-composer-pipelines-test-2019-09-10/addon/pipelines/home#!/results/16/steps/%7Beaef96f3-1705-452a-b6c6-5e0479dd6e3e%7D)
- [neither of the above, vr tests skipped](https://bitbucket.org/ataylorme/example-wp-composer-pipelines-test-2019-09-10/addon/pipelines/home#!/results/19/steps/%7Bf2cc28b4-13e3-42f8-a445-ad9550ec39d0%7D)

**Comment by aaronbauman** [comment]
Working after clearing pipelines cache and rerunning.

**Comment by aaronbauman** [comment]
Nope, spoke too soon.
Still choking on this error.
https://bitbucket.org/messageagency/pipe-test/addon/pipelines/home#!/results/36/steps/%7B59e162a2-25c0-449e-9ab4-364026a5f62b%7D

I've followed steps to run pipelines locally https://medium.com/@steveliles/debugging-bitbucket-pipelines-locally-35d13f1adcd5 but of course I can't recreate the problem - same command works fine in local docker.

**Comment by greg-1-anderson** [comment]
It could have something to do with the shallow clone.

**Comment by aaronbauman** [comment]
OK, this is resolved after i eliminated all other variables:
- opened an entirely new PR
- deleted all pipeline caches
- restored all ci files to match from https://github.com/pantheon-systems/example-drops-8-composer/pull/278
