### ISSUE TITLE
Consider Removing Local Drush from Upstream

### ISSUE THREAD

**Issue by sambasile** [pantheon-systems/example-drops-8-composer#302]
When using this upstream I now remove the local Drush as part of my installation.  If not removed, it often conflicts with running Drush commands from Terminus in the Dev environment especially when the versions get out of sync.

**Comment by greg-1-anderson** [comment]
We can and should fix the 'out of sync' problem on the platform. Drush 9, perhaps?

**Comment by greg-1-anderson** [comment]
Pantheon will now call any site-local Drush directly, without redispatching through the global Drush. This should clear up any conflicts.

Also, this is just an example repository; feel free to remove or adjust any dependencies as needed to suit your particular project.
