### ISSUE TITLE
Update settings.php to latest Drupal 8.8.0 recommendations.

### ISSUE THREAD

**Issue by andileco** [pantheon-systems/example-drops-8-composer#325]
- Use $settings["file_temp_path"] instead of $config[system.file][path][temporary].
- Use $settings['config_sync_directory'] instead of $config_directories[CONFIG_SYNC_DIRECTORY].

**Comment by greg-1-anderson** [comment]
Related to https://github.com/pantheon-systems/drops-8/pull/286

**Comment by alisonjo315** [comment]
Or is it "update settings.php to latest Drupal 8.8.0" (not settings.pantheon.php, which isn't in this repo, and has already been updated in drops-8-scaffolding)?

(i.e. this file needs to be updated, just like settings.pantheon.php was updated in the PR above -- )
https://github.com/pantheon-systems/example-drops-8-composer/blob/master/web/sites/default/settings.php

**Comment by alisonjo315** [comment]
The following change worked for me on our sites -- I'll submit a PR to this effect, hope it's what's needed!
```
-$config_directories = array(
-  CONFIG_SYNC_DIRECTORY => dirname(DRUPAL_ROOT) . '/config',
-);
+$settings['config_sync_directory'] = dirname(DRUPAL_ROOT) . '/config';
```

**Comment by ChristopherMatthews** [comment]
A bit confused...I'm using example-drops-8-composer. Do we need to make the same [changes that were made in drops-8](https://github.com/pantheon-systems/drops-8/pull/286/commits/192ab467dcd07723f5ec038ea6a97e9d855ec5c2) in both settings.pantheon.php and settings.php?

The confusing part (for me) is that the following change can only be done in settings.pantheon.php
```
if (isset($_ENV['PANTHEON_ENVIRONMENT'])) {
  $config['system.file']['path']['temporary'] = $_SERVER['HOME'] .'/tmp';
  $settings["file_temp_path"] = $_SERVER['HOME'] .'/tmp';
}
```

**Comment by ChristopherMatthews** [comment]
### Changes to settings.pantheon.php

**Change #1**
```
if ($is_installer_url) {
-  $config_directories = array(
-    CONFIG_SYNC_DIRECTORY => 'sites/default/files',
-  );
+  $settings['config_sync_directory'] =  'sites/default/files';
}
else {
-  $config_directories = array(
-    CONFIG_SYNC_DIRECTORY => 'sites/default/config',
-  );
+  $settings['config_sync_directory'] = 'sites/default/config';
}

```
**Change #2**
```
if (isset($_ENV['PANTHEON_ENVIRONMENT'])) {
-  $config['system.file']['path']['temporary'] = $_SERVER['HOME'] .'/tmp';
+  $settings["file_temp_path"] = $_SERVER['HOME'] .'/tmp';
}
```

### Change to settings.php
-  $config_directories = array(
-    CONFIG_SYNC_DIRECTORY => 'sites/default/config',
-  );
+  $settings['config_sync_directory'] = 'sites/default/config';
}

Is this above correct?

**Comment by greg-1-anderson** [comment]
Fixed by #326

**Comment by ChristopherMatthews** [comment]
@greg-1-anderson, so if started with example-drops-8-composer then I **do not** need to touch settings.pantheon.php, correct? I **ONLY** need to make the config directory change to my settings.php, correct?

**Comment by alisonjo315** [comment]
@ChristopherMatthews To your earlier comment, I think the original issue submitter copied from the version of this issue on drops-8, so the issue title and description are a little off (re: affected filename and temp directory).  But anyway, I'm pretty sure you need to update both files:
![image](https://user-images.githubusercontent.com/2660348/71299140-cc9b1b00-2359-11ea-8ac9-499576735016.png)

Note: To be clear, I'm just a user, I don't work for Pantheon :) That said, FWIW: We added `@drupal-scaffold` to `post-update-cmd` in our composer.json, so we get updates to the two scaffolding files specified in the "example-drops-8-composer" composer.json file (including settings.pantheon.php) -- so, in our case, the change to settings.pantheon.php happened automatically -- then I had to follow up with the change to settings.php.

Hope this helps!  And if Greg chimes in that I got something wrong, I'll update this comment...

**Comment by ChristopherMatthews** [comment]
Thanks @alisonjo315, I manually updated pantheon.settings.php **and** settings.php per your suggestions above and it looks like that did the trick. @greg-1-anderson, is there a reason why @drupal-scaffold is currently not part of the post-update-cmd script in example-drops-8-composer? This is what I have now in my scripts section now...

```
"scripts": {
        "build-assets": [
            "@prepare-for-pantheon",
            "composer install --optimize-autoloader --no-dev"
        ],
        "drupal-scaffold": "DrupalComposer\\DrupalScaffold\\Plugin::scaffold",
        "prepare-for-pantheon": "DrupalProject\\composer\\ScriptHandler::prepareForPantheon",
        "post-install-cmd": [
            "@drupal-scaffold",
            "DrupalProject\\composer\\ScriptHandler::createRequiredFiles"
        ],
        "post-update-cmd": [
            "@drupal-scaffold",
            "DrupalProject\\composer\\ScriptHandler::createRequiredFiles"
        ],
        "post-create-project-cmd": [
            "@drupal-scaffold",
            "DrupalProject\\composer\\ScriptHandler::createRequiredFiles"
        ]
```
