### ISSUE TITLE
config_installer is obsolete; use core feature instead

### ISSUE THREAD

**Issue by ptmkenny** [pantheon-systems/example-drops-8-composer#375]
In https://github.com/pantheon-systems/example-drops-8-composer/blob/master/composer.json

According to the [Config Installer](https://www.drupal.org/project/config_installer) module's project page:

> This project is deprecated
> 
> As of Drupal core 8.6 now supports Installing Drupal from configuration.
> 
> There will no Drupal 9 version

**Comment by greg-1-anderson** [comment]
Removed in #399
