### ISSUE TITLE
Drops 8 Scaffolding Failing

### ISSUE THREAD

**Issue by danheisel** [pantheon-systems/example-drops-8-composer#383]
Hi. Just ran a Composer update command on a site that needs to go from 8.8.5 to 8.8.6 and was met with some download errors with the drops-8-scaffolding.

` Has failed with the last source: https://raw.githubusercontent.com/pantheon-systems/drops-8-scaffolding/{version}/{path}
Script DrupalComposer\DrupalScaffold\Plugin::scaffold handling the drupal-scaffold event terminated with an exception
  [Exception]
  Failed to download:
  https://raw.githubusercontent.com/pantheon-systems/drops-8-scaffolding/8.8.6/.gitattributes
  https://raw.githubusercontent.com/pantheon-systems/drops-8-scaffolding/8.8.6/.ht.router.php
  https://raw.githubusercontent.com/pantheon-systems/drops-8-scaffolding/8.8.6/index.php
  https://raw.githubusercontent.com/pantheon-systems/drops-8-scaffolding/8.8.6/robots.txt
  https://raw.githubusercontent.com/pantheon-systems/drops-8-scaffolding/8.8.6/sites/default/default.services.yml
  https://raw.githubusercontent.com/pantheon-systems/drops-8-scaffolding/8.8.6/sites/default/default.settings.php
  https://raw.githubusercontent.com/pantheon-systems/drops-8-scaffolding/8.8.6/sites/development.services.yml
  https://raw.githubusercontent.com/pantheon-systems/drops-8-scaffolding/8.8.6/sites/example.settings.local.php
  https://raw.githubusercontent.com/pantheon-systems/drops-8-scaffolding/8.8.6/sites/example.sites.php
  https://raw.githubusercontent.com/pantheon-systems/drops-8-scaffolding/8.8.6/update.php
  https://raw.githubusercontent.com/pantheon-systems/drops-8-scaffolding/8.8.6/sites/default/default.services.pantheon.preproduction
  .yml
  https://raw.githubusercontent.com/pantheon-systems/drops-8-scaffolding/8.8.6/sites/default/settings.pantheon.php`

Looks like 8.8.6 is not ready for this repo yet, I guess. Maybe I'm in the wrong spot though. If I am in the correct spot, any idea when it will be ready or a way around this? Thanks!

**Comment by greg-1-anderson** [comment]
There is always a delay after the release of any new Drupal version before the drops-8-scaffolding repo gets the corresponding tag. Usually, it is tagged within a couple of hours. For 8.8.6, there were some problems with the release, so it took a couple of days. This is unusual.

You can avoid the need to wait for the drops-8-scaffolding tag by switching to drupal/core-composer-scaffold. See the current HEAD of master for this repo for an example of how to do that.
