### ISSUE TITLE
Command "prepare-for-pantheon" is not defined.

### ISSUE THREAD

**Issue by joshkoenig** [pantheon-systems/example-drops-8-composer#43]
Internal bug report from Lauren came in through support chat:

Based on the instructions here https://github.com/pantheon-systems/example-drops-8-composer both the upstream and manual installs are failing.

We cannot see the exact issue on the upstream installs, but on the manual installs, we are seeing the following error:
[Symfony\Component\Console\Exception\CommandNotFoundException]
Command "prepare-for-pantheon" is not defined.

Joseph Bonilla looked and saw that https://github.com/pantheon-systems/example-drops-8-composer/blob/master/composer.json#L46-L50 was not in his local copy.

**Comment by uceap-web** [comment]
Using older terminus version, 0.13.6 and running:

`terminus composer update --site=sitename --env=dev` (worked!)
`terminus composer <sitename>.<dev> update` (error!)

**Comment by greg-1-anderson** [comment]
Fixed and updated the manual install instructions both in the README and in the [original blog post](https://pantheon.io/blog/using-composer-relocated-document-root-pantheon)
