### ISSUE TITLE
Command "prepare-for-pantheon" terminated with an exception

### ISSUE THREAD

**Issue by lisastreeter** [pantheon-systems/example-drops-8-composer#49]
I am using the Manual Setup instructions. When I execute:
$ composer prepare-for-pantheon

I get an exception:
```
  [Symfony\Component\Finder\Exception\AccessDeniedException]                                                        
  RecursiveDirectoryIterator::__construct(/Users/lisastreeter/Desktop/Sync/worthington/vendor/dflydev/dot-access-c  
  onfiguration/.git): failed to open dir: No such file or directory  
```                                               
  and:                                                                     
```
 [UnexpectedValueException]                                                                                        
  RecursiveDirectoryIterator::__construct(/Users/lisastreeter/Desktop/Sync/worthington/vendor/dflydev/dot-access-c  
  onfiguration/.git): failed to open dir: No such file or directory    
```

Before I run the prepare-for-pantheon command, the .git directory does exist in that location. After I run the command, the .git directory is no longer there. So it seems like it's trying to remove the same directory twice.

**Comment by greg-1-anderson** [comment]
I recently fixed this in HEAD of master, but forgot to tag a new release. I just pushed a 1.0.5 tag. Please update to this tag or HEAD of master and try again.

**Comment by lisastreeter** [comment]
Thank you! That worked.
