### ISSUE TITLE
build-assets is not registered in Composer

### ISSUE THREAD

**Issue by xohail** [pantheon-systems/example-drops-8-composer#54]
Hi!

`composer -n build-assets returns` 
**[Symfony\Component\Console\Exception\CommandNotFoundException]  
  Command "build-assets" is not defined.**

As a result the build fails.

**Comment by greg-1-anderson** [comment]
What are your steps to reproduce? The [build-assets script definition](https://github.com/pantheon-systems/example-drops-8-composer/blob/1.0.5/composer.json#L47) exists in the current release, and on the master branch. Also, it is used in the Circle tests, which are passing, so I'm not sure why it is not working for you.

**Comment by xohail** [comment]
Should I provide you with the circle.yml file to find the steps ?

**Comment by greg-1-anderson** [comment]
Link to the GitHub repo / failed Circle run would do, if they're public. Did you modify the composer.json? Does it still contain the `script` section with `build-assets`?

**Comment by xohail** [comment]
Oh! `composer.json` was not pushed after changes. Thank you for the help.

**Comment by xohail** [comment]
@greg-1-anderson 
I have a Drupal-7 Pantheon site.
The repository for the site is maintained on bitbucket.
When the build is run, it fails on `composer -n build-assets` with error: 
![build 1](https://cloud.githubusercontent.com/assets/5494101/22664382/4579472a-ecd2-11e6-9e29-33d6b0b55572.png)
I know `composer.json` has the build-assets which is missing in my repository obviously. 
Should I copy all the contents of this repository `example-drops-8-composer`to get it functional?

If `composer -n build-assets` is commented, the build fails with error:
![build 2](https://cloud.githubusercontent.com/assets/5494101/22664490/bd99d4e0-ecd2-11e6-978f-da77376e62c4.png)
during the multi-dev creation.

**Comment by greg-1-anderson** [comment]
You're breaking new ground if you use the build-env tool with Drupal 7. I started to make a Drupal 7 version, but haven't finished it yet. It's on my list to get that working near the end of this sprint (in the next three weeks). If you tackle this on your own, you'll definitely want to copy the configuration steps from this project's circle.yml, and ensure that the build-assets script is defined and, at a minimum, runs `composer install` or `composer update`.

**Comment by stevector** [comment]
`build-assets` is a script in the D7 example repo: https://github.com/pantheon-systems/example-drops-7-composer/blob/master/composer.json#L63

I think we can close this issue now.
