### ISSUE TITLE
Asking for password

### ISSUE THREAD

**Issue by xohail** [pantheon-systems/example-drops-8-composer#55]
Copied the repository.
Tried the first build.
But fails at `terminus build-env:delete:ci -n "$TERMINUS_SITE" --keep=2 --yes`
Asks for password. I am using my pantheon site as $TERMINUS_SITE.
Here is the screen-shot:
http://screenshotlink.ru/0f3abcb62a1ac6bbe58358df5816735e.png

**Comment by stevector** [comment]
@xohail That command `terminus build-env:delete:ci` relies on ssh to read information from sites. Your CircleCI environment needs an ssh key to do that interaction without a password.

@greg-1-anderson, is there a way we can make that more self-evident?

**Comment by greg-1-anderson** [comment]
@stevector I don't think that we can detect whether or not we have permissions. We could potentially detect that Circle has **no** permissions.

The main problem we have here is that there is no public documentation on the setup process for circle.yml usage. I'll be working on a guide for that in the next sprint; maybe interested parties can review and try the draft.

**Comment by xohail** [comment]
Any one having the same issue:

1. Generate the ssh key
2. Add public key to GitHub/BitBucket
3. Add same public key to Pantheon
4. Add **PRIVATE** key to circle ci using _SSH permissions_ tab

**Comment by aidenwalker42** [comment]
HOW DO I GENERATE AN SSH KEY GOD DAMMIT
