### ISSUE TITLE
Repository mismatch issue

### ISSUE THREAD

**Issue by xohail** [pantheon-systems/example-drops-8-composer#57]
![capture](https://cloud.githubusercontent.com/assets/5494101/22658043/84eb49e8-ecba-11e6-8bbc-090a03fe685f.png)

How do you associate the repository with the pantheon site.

**Comment by xohail** [comment]
I have cloned mysite-dev to mysite folder on local
cd to mysite
Added bitbucket repo `git remote add bitbucket git@bitbucket.org:Imxohail/mysite-ci.git`
Pushed contents to bitbucket
Build fails with same error of mismatch repo.

Any idea ?

**Comment by greg-1-anderson** [comment]
That error message is very dissatisfying. I'll make a fix to the build-env delete command to print both of the repositories that it's using in its check.

**Comment by greg-1-anderson** [comment]
I see; the other repository is there, it's just empty. The "associated" repository comes from the file `code/build-metadata.json`, which should be written by `build-env:create` when the multidev branch is created. Does this file exist in all of your environments whose name starts with 'ci-'?  Are you using `build-env:create` to create all multidev sites whose name starts with 'ci-'?

**Comment by xohail** [comment]
I don't think so it exists.
`ci-` multi-dev was created using build previously.
What steps do you suggest to avoid this issue ?

**Comment by greg-1-anderson** [comment]
Post the contents of one of these files here.

**Comment by greg-1-anderson** [comment]
If your `ci-` multi-devs are very very old, just delete all of them by hand, from your Pantheon dashboard. If you want to keep any of them, create a new multidev from them first with a name that does not begin with `ci-`.

**Comment by xohail** [comment]
Thanks @greg-1-anderson . Deleting the older `ci-` multi-devs resolved the issue.
