### ISSUE TITLE
Composer Merge Plugin Question

### ISSUE THREAD

**Issue by mbosma** [pantheon-systems/example-drops-8-composer#82]
Would you consider adding a way for forks to include an additional composer.json file for customization? Maybe composer-local.json and merging it with the composer merge plugin. If so, I'll work on it and provide a pull request. If not, is the best practice to merge your changes into our custom composer.json every time it updates?

`"require" : {`
    `    "wikimedia/composer-merge-plugin": "dev-master"`
`},`
`"extra": {`
    `    "merge-plugin": {`
        `        "include": [ "composer-local.json" ]`
    `    }`
`}`

**Comment by greg-1-anderson** [comment]
This is being discussed in #61. We have considered doing something like that, but at the moment are focused on refining the MVP workflow for this project. That goal has nearly been reached.

The current assumed use-case is that folks will clone this project via `composer create-project`, probably by using the [Terminus Build Tools Plugin](https://github.com/pantheon-systems/terminus-build-tools-plugin) command of the same name. Thereafter, a project may remain forked, or you may add another remote to this project to pull in future enhancements, resolving conflicts as necessary. The update workflow has not been addressed much yet, but when it is, separating the boilerplate out will help make that process easier.

Note that `composer require` will add newly required projects to the primary `composer.json`, so we want that file to be the minimal / user-modified file, and the external composer.json should contain the bits provided by the upstream.
