### ISSUE TITLE
drops-8/8.3.6/.gitattributes" file could not be downloaded

### ISSUE THREAD

**Issue by jhammars** [pantheon-systems/example-drops-8-composer#98]
Composer update fails and returns this message:

[Composer\Downloader\TransportException]                                                                                                The "https://raw.githubusercontent.com/pantheon-systems/drops-8/8.3.6/.gitattributes" file could not be downloaded (HTTP/1.1 404 Not Found)       

It looks like the proper path would be: https://raw.githubusercontent.com/pantheon-systems/drops-8/update-8.3.6/.gitattributes

**Comment by greg-1-anderson** [comment]
The 8.3.6 tag was inadvertently not pushed to the drops-8 repository. This has been fixed. Sorry for the inconvenience.

**Comment by jhammars** [comment]
Thanks for fixing!
